2018-01-28 22:20:01,819 ERROR: Exception on /search [GET] [in /Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sergiiholodnuk/wifi_flask/app/main/routes.py", line 144, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'list' and 'int'
2018-01-28 22:20:31,863 ERROR: Exception on /search [GET] [in /Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sergiiholodnuk/wifi_flask/app/main/routes.py", line 144, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'list' and 'int'
2018-01-28 22:21:31,898 ERROR: Exception on /search [GET] [in /Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sergiiholodnuk/wifi_flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sergiiholodnuk/wifi_flask/app/main/routes.py", line 144, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'list' and 'int'
2018-01-28 22:24:26,869 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 22:41:27,421 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 22:42:10,464 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 22:43:33,578 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 22:45:30,745 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 22:50:33,740 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:75]
2018-01-28 23:20:49,443 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
2018-01-28 23:22:18,330 INFO: wifi flask startup [in /Users/sergiiholodnuk/wifi_flask/app/__init__.py:76]
